#!/usr/bin/env ruby

require 'json'
require 'erb'

case ARGV[0]
    when "set_conf"
        conf = JSON.parse(ARGV[1])
        puts "Setting conf #{ARGV[1]}"

        # save new configuration
        File.open("./agent_conf","w") do |f|
          f.write conf.to_json
        end

        # update application
        File.open("config/config.yml", "w") do |f|
          f.write ERB.new(File.new("config.yml.erb").read).result(binding)
        end

        # propagate update to application
        # void - done on container level
    when "get_conf"
        puts File.new("./agent_conf").read
    else
        puts "Unknown argument"
        exit -1
end

